-- MySQL Script generated by MySQL Workbench
-- Wed Dec 18 15:14:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbFilms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbFilms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbFilms` DEFAULT CHARACTER SET utf8 ;
USE `dbFilms` ;

-- -----------------------------------------------------
-- Table `dbFilms`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbFilms`.`genre` (
  `idgenre` INT NOT NULL AUTO_INCREMENT,
  `nomGenre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idgenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFilms`.`realisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbFilms`.`realisateur` (
  `idrealisateur` INT NOT NULL AUTO_INCREMENT,
  `realisateur` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idrealisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbFilms`.`films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbFilms`.`films` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `annee-sortie` VARCHAR(50) NOT NULL,
  `idgenre` INT NOT NULL,
  `idrealisateur` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_films_genre_idx` (`idgenre` ASC),
  INDEX `fk_films_realisateur1_idx` (`idrealisateur` ASC),
  CONSTRAINT `fk_films_genre`
    FOREIGN KEY (`idgenre`)
    REFERENCES `dbFilms`.`genre` (`idgenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_films_realisateur1`
    FOREIGN KEY (`idrealisateur`)
    REFERENCES `dbFilms`.`realisateur` (`idrealisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
